// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnmYcRu3lTyJ8dE_Z3PzyIdYAGWpurfu4',
    appId: '1:326947707190:web:44da7e7f4b9ccb0f3e3b97',
    messagingSenderId: '326947707190',
    projectId: 'nu-lost-and-found-c32d7',
    authDomain: 'nu-lost-and-found-c32d7.firebaseapp.com',
    storageBucket: 'nu-lost-and-found-c32d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgfjekLhJyTPk14BdakO-7ReMxkqmS3Qs',
    appId: '1:326947707190:android:9df22e92e6648c313e3b97',
    messagingSenderId: '326947707190',
    projectId: 'nu-lost-and-found-c32d7',
    storageBucket: 'nu-lost-and-found-c32d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNiR7sAbz_0da6OTqBRwZBElJqGZYQeZQ',
    appId: '1:326947707190:ios:80d71b8252af72df3e3b97',
    messagingSenderId: '326947707190',
    projectId: 'nu-lost-and-found-c32d7',
    storageBucket: 'nu-lost-and-found-c32d7.firebasestorage.app',
    iosBundleId: 'com.example.nuLostAndFound',
  );

}